### ISSUE TITLE
run_preprocess.py: error: unrecognized arguments: cat-pikachu-0 cat quad 0

### ISSUE THREAD

**Issue by Jinbeizame02** [lab4d-org/lab4d#23]

**Comment by Jinbeizame02** [comment]
python scripts/run_preprocess.py cat-pikachu-0 cat quad "0"
Traceback (most recent call last):
  File "C:\Users\lab4d\scripts\run_preprocess.py", line 25, in <module>
    track_anything_module = importlib.import_module(
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\lab4d\preprocess\third_party\Track-Anything\app.py", line 10, in <module>
    from track_anything import TrackingAnything
ModuleNotFoundError: No module named 'track_anything'

**Comment by randomx207** [comment]
hi, have you solved this?
