### ISSUE TITLE
[Bug/issue] when I use custom video, I encounter an error

### ISSUE THREAD

**Issue by limaolin2017** [lab4d-org/lab4d#41]
**Describe the bug**

**To Reproduce**

I follow the step:
Interactive segmentation: [Track-Anything](https://github.com/gaomingqi/Track-Anything) will be used given text prompt “other”, e.g.,:
python scripts/run_preprocess.py cat-pikachu-0 cat quad "0"

**Additional context**

Initializing BaseSegmenter to cuda:0
Traceback (most recent call last):
  File "/root/autodl-tmp/lab4d/scripts/run_preprocess.py", line 147, in <module>
    track_anything_gui(vidname)
  File "/root/autodl-tmp/lab4d/preprocess/third_party/Track-Anything/app.py", line 529, in track_anything_interface
    model = TrackingAnything(SAM_checkpoint, gdino_checkpoint, xmem_checkpoint, e2fgvi_checkpoint, args)
  File "/root/autodl-tmp/lab4d/preprocess/third_party/Track-Anything/track_anything.py", line 18, in __init__
    self.samcontroler = SamControler(
  File "/root/autodl-tmp/lab4d/preprocess/third_party/Track-Anything/tools/interact_tools.py", line 40, in __init__
    self.sam_controler = BaseSegmenter(SAM_checkpoint, model_type, device)
  File "/root/autodl-tmp/lab4d/preprocess/third_party/Track-Anything/tools/base_segmenter.py", line 25, in __init__
    self.model = sam_model_registry[model_type](checkpoint=SAM_checkpoint)
  File "/root/miniconda3/envs/lab4d/lib/python3.9/site-packages/segment_anything/build_sam.py", line 15, in build_sam_vit_h
    return _build_sam(
  File "/root/miniconda3/envs/lab4d/lib/python3.9/site-packages/segment_anything/build_sam.py", line 105, in _build_sam
    state_dict = torch.load(f)
  File "/root/miniconda3/envs/lab4d/lib/python3.9/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/root/miniconda3/envs/lab4d/lib/python3.9/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by gengshan-y** [comment]
Hi, I would suggest checking whether there are missing checkpoints, specifically whether the location `SAM_checkpoint` points to is empty.

All checkpoints should have been downloaded [with these line](https://github.com/gengshan-y/Track-Anything/blob/73778091905626aaca2d6fa50fe2f0e11bc49403/app.py#L518-L521).

**Comment by limaolin2017** [comment]
Thank you, its fixed via download again
